spring:
  application:
    name: office-manager
  data:
    mongodb:
      database: office-manager
  rabbitmq:
    host: localhost
    template:
      exchange: topic
      queues: office, flights



